### PR TITLE
fix testimonials behaviour

### LINKED ISSUE #56: Fix testimonials behaviour
### What's the current

* there're no testimonials but right button for horizontal scrolling is enabled
* clicking it enables left button
* clicking left button the number of times the right button was clicked it gets disabled
* it looks like there're infinite number of invisible testimonial cards

### How it should be

both horizontal scrolling buttons should be disabled

### PR DESCRIPTION
**Pull request by jagdishlove**
- When there is no Testimonials, we will be hiding the arrows and pagination in carousel slider.
- When the total page size is > 1 then only we will enable and make arrows and carousel slider otherwise it will be hidden, this is for better user intaction to not confuse them.

closes #56

### CODE REVIEW

File: src/components/core/paginatedCards/PaginatedCards.tsx [hunk 1]
```diff
@@ -36,6 +36,7 @@ export function PaginatedCards({
   const visibleCards = cards.slice(startIndex, endIndex);
 
   const nextCardElement = cards[endIndex];
+  const shouldShowNavigation = totalPages > 1;
```
Comment (aricionur) [inline src/components/core/paginatedCards/PaginatedCards.tsx:39]: please can you rearrange this as `showNavigation`,
it is shorter and  more clear : )
Thanks

**Review by aricionur — CHANGES_REQUESTED** [review]
